### PR TITLE
Add Persian layout

### PR DESCRIPTION
**Pull request by mhdzli**

### CODE REVIEW

**Comment by mhdzli** [comment]
@anjandev 
Is it decided if you want to split up the keymap file?

**Comment by proycon** [comment]
No, we're keeping things as they are. I'm looking at your patch and will be merging it shortly! Thanks!

**Comment by mhdzli** [comment]
@proycon 
Thank you for your great job.
It makes using pinephone much easier for me.

**Comment by proycon** [comment]
Thanks! This is now merged!

**Pull request closed without merging**
