### PR TITLE
Support multiple outputs

### PR DESCRIPTION
**Pull request by mojyack**
Currently wvkbd always appears on the first display.
This patch allows wvkbd to appear on other displays than that.

Tested on sway-1.8.1
This may also solve #38

### CODE REVIEW

**Comment by proycon** [comment]
Thanks a lot! This is a nice improvement. With this patch, wvkbd starts on the current display, rather than on the first one.

As an extra feature, it might be an idea to have a command line parameter to set explicitly set the display.

**Comment by proycon** [comment]
@mojyack I just identified a problem caused by this patch: it seems something is off with the scaling. On a mobile device with sxmo, all letters are slightly blurred now whereas without this patch they are crisp. I'll see if I can find a remedy.

**Comment by proycon** [comment]
Should be fixed now in d7d17ff4abbd242b07f2fb79f87e372ef15c2361

**Comment by mojyack** [comment]
Thanks!

**Pull request merged**
