### PR TITLE
Resize keyboard at correct timing (v2)

### LINKED ISSUE #45: Incorrect layout is drawn after hide/show
Tested on Sway-1.8.1 + wvkbd-HEAD(6e52be343d66a3c1ae595d2126294615ea4f6760)
How to reproduce:
1. toggle layout with NextLayer key
2. hide with 'kill -s 34'
3. show with 'kill -s 34'
4. the last layout is drawn, but the actual layout is keyboard.layouts[0].

This is caused by an order of flip_landscape() and kbd_draw_layout().
When showing the keyboard, kbd_draw_layout() is called by xdg_popup_configure()->kbd_resize(). And then the keyboard layout is reset to 0 in wl_surface_enter()->flip_landscape().

### PR DESCRIPTION
**Pull request by mojyack**
This is version 2 of #46 _(fix #45)_
#46 depends on Sway specific behavior and I fixed that.

Tested on sway-1.8.1 and hyprland-0.30.0

### CODE REVIEW

**Comment by proycon** [comment]
Thanks! Everything seemed to be in order but when I sent a SIGINT to wvkbd after having sent SIGRTMIN a few times and being done testing, my entire Hyprland session crashed to my surprise! Of course, this may be a bug in Hyprland itself rather than in this patch; I attach the log for reference. I don't suppose you experienced anything similar on your Hyprland test or have any clue what may cause this?

If I don't send SIGRTMIN, it exits fine.

```
--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
I hope you didn't have any unsaved progress.

Hyprland received signal 11 (Segmentation fault)

Version: 1b48642fd15c433c53876f1b933dcd46265caf8f
Tag: v0.30.0

System info:
	System name: Linux
	Node name: pollux
	Release: 6.5.9-arch2-1
	Version: #1 SMP PREEMPT_DYNAMIC Thu, 26 Oct 2023 00:52:20 +0000

GPU:
	03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] [1002:73ff] (rev c1) (prog-if 00 [VGA controller])
17:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev c9) (prog-if 00 [VGA controller])


os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://bugs.archlinux.org/"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo
	


Backtrace:
	#0 | Hyprland(_Z12getBacktracev+0x62) [0x55b10226ef92]
		??
		??:0
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x51e) [0x55b1022455fe]
		??
		??:0
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x47) [0x55b1021ca047]
		??
		??:0
	#3 | /usr/lib/libc.so.6(+0x3e710) [0x7f6662037710]
		??
		??:0
	#4 | Hyprland(+0x19fc32) [0x55b1022c8c32]
		??
		??:0
	#5 | /usr/lib/libwayland-server.so.0(+0xb9ba) [0x7f66629039ba]
		??
		??:0
	#6 | /usr/lib/libwayland-server.so.0(wl_client_destroy+0xab) [0x7f66629040db]
		??
		??:0
	#7 | /usr/lib/libwayland-server.so.0(+0xc60e) [0x7f666290460e]
		??
		??:0
	#8 | /usr/lib/libwayland-server.so.0(wl_event_loop_dispatch+0xa2) [0x7f6662903ae2]
		??
		??:0
	#9 | /usr/lib/libwayland-server.so.0(wl_display_run+0x27) [0x7f66629042d7]
		??
		??:0
	#10 | Hyprland(main+0x8d6) [0x55b1021b4ea6]
		??
		??:0
	#11 | /usr/lib/libc.so.6(+0x27cd0) [0x7f6662020cd0]
		??
		??:0
	#12 | /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f6662020d8a]
		??
		??:0
	#13 | Hyprland(_start+0x25) [0x55b1021c6a45]
		??
		??:0


Log tail:
[LOG] Searching for matching rules for foot (title: proycon@pollux:~)
[LOG] Window 55b1060a2170 set title to proycon@pollux:~
[LOG] New XDG Popup mapped at 0 0
[LOG] Registered signal for owner 55b10607f730: 55b106035820 -> 55b10607f738 (owner: CWLSurface)
[LOG] CWLSurface 55b10607f730 called init()
[LOG] Registered signal for owner 55b10607d320: 55b106035810 -> 55b10607d398 (owner: SurfaceTreeNode)
[LOG] Registered signal for owner 55b10607d320: 55b1060357e0 -> 55b10607d400 (owner: SurfaceTreeNode)
[LOG] Registered signal for owner 55b10607d320: 55b106035820 -> 55b10607d468 (owner: SurfaceTreeNode)
[LOG] Creating a surfaceTree Root! [Window nullptr]
[LOG] XDG Popup got assigned a surfaceTreeNode 55b10607d320
[LOG] Cleanup: destroyed a layersurface
[LOG] Set keyboard focus to surface 55b105f456d0, with [Window 55b106014420: title: "./wvkbd-mobintl (pollux:wvkbd)"]
[LOG] Enable TextInput
[LOG] Disable TextInput
[LOG] IME TextInput Keyboard Grab new
[LOG] Registered signal for owner 55b106010350: 55b1060981a0 -> 55b106010360 (owner: IME Keyboard Grab)
[LOG] Callback 55b106010388 -> 55b106010380, IME Keyboard Grab removed.
[LOG] IME TextInput Keyboard Grab destroy
[LOG] XDG Popup unmapped
[LOG] Callback 55b10607d428 -> 55b10607d420, SurfaceTreeNode removed.
[LOG] Callback 55b10607d490 -> 55b10607d488, SurfaceTreeNode removed.
[LOG] Callback 55b10607d3c0 -> 55b10607d3b8, SurfaceTreeNode removed.
[LOG] SurfaceTree Node removed
[LOG] Callback 55b10607f760 -> 55b10607f758, CWLSurface removed.
[LOG] CWLSurface 55b10607f730 called destroy()
[LOG] Destroyed popup XDG 55b103500670
[LOG] Callback 55b1035008c8 -> 55b1035008c0, HyprPopup removed.
[LOG] Callback 55b103500860 -> 55b103500858, HyprPopup removed.
[LOG] Callback 55b1035007f8 -> 55b1035007f0, HyprPopup removed.
[LOG] Callback 55b103500790 -> 55b103500788, HyprPopup removed.
[LOG] Callback 55b103500728 -> 55b103500720, HyprPopup removed.
[LOG] Callback 55b1035006c0 -> 55b1035006b8, HyprPopup removed.
[LOG] Callback 55b105ff5018 -> 55b105ff5010, Keyboard removed.
[LOG] Callback 55b105ff4ee0 -> 55b105ff4ed8, Keyboard removed.
[LOG] Callback 55b105ff4f48 -> 55b105ff4f40, Keyboard removed.
[LOG] Callback 55b105ff4fb0 -> 55b105ff4fa8, Keyboard removed.
[LOG] Destroyed keyboard 55b105ff4eb0
[LOG] LayerSurface 55b106017050 unmapped
[LOG] Framebuffer created, status 36053
[LOG] Callback 55b103ae2eb0 -> 55b103ae2ea8, CWLSurface removed.
[LOG] CWLSurface 55b103ae2e80 called destroy()
[LOG] LayerSurface 55b106017050 destroyed
[LOG] Callback 55b103ae3068 -> 55b103ae3060, layerSurface removed.
[LOG] Callback 55b103ae2f30 -> 55b103ae2f28, layerSurface removed.
[LOG] Callback 55b103ae2f98 -> 55b103ae2f90, layerSurface removed.
[LOG] Callback 55b103ae3000 -> 55b103ae2ff8, layerSurface removed.
[LOG] Callback 55b103ae30d0 -> 55b103ae30c8, layerSurface removed.
[LOG] LayerSurface 55b105fe3cf0 arranged: x: 2160 y: 3811 w: 3840 h: 29 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] LayerSurface 55b105f09850 arranged: x: 2160 y: 1680 w: 3840 h: 2160 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] Monitor DP-2 layers arranged: reserved: [0.00000, 0.00000] [0.00000, 29.00000]
```

**Comment by proycon** [comment]
Some further testing: If I send SIGRTMIN and the keyboard is hidden state, it also exits fine.

**Comment by mojyack** [comment]
Thanks for your report!
I confirmed that hyprland crash problem.
I'll look into it.

**Comment by mojyack** [comment]
I found that this bug is not related to this patch.
This is introduced by "Support fractional-scale-v1"(730e97038cf2d2ff9cbfe7a15c863498fb832c29).
The actual crash happens at `handleAddonDestroy(Hyprland/src/protocols/FractionalScale.cpp)`

**Comment by mojyack** [comment]
The above commit should solve the problem.

**Comment by mojyack** [comment]
I opened [an issue](https://github.com/hyprwm/Hyprland/issues/3735) on Hyprland side.
This time it was completely a client-side fault, but the server shouldn't crash anyway.

**Comment by proycon** [comment]
Perfect! Great work! Merged now!

Also great this is also solved on the Hyprland side now.

**Pull request merged**
